name: Check PHP code style

on:
  pull_request:
    branches: [main]
    paths:
      - "**.php"
      - "composer.json"

jobs:
  php-code-styling:
    name: check-php-code-style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.3"
          coverage: none

      - name: Install composer dependencies
        uses: ramsey/composer-install@v3

      - name: Check PHP code style
        run: vendor/bin/pint --test
